"""created

Revision ID: 541a54bf0546
Revises: ffe809a51166
Create Date: 2026-07-06 17:19:07.220644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '541a54bf0546'
down_revision: Union[str, Sequence[str], None] = 'ffe809a51166'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movie', 'year',
               existing_type=sa.DATE(),
               type_=sa.Integer(),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movie', 'year',
               existing_type=sa.Integer(),
               type_=sa.DATE(),
               existing_nullable=False)
    # ### end Alembic commands ###
