"""created

Revision ID: ffe809a51166
Revises: 5504fbdc52c7
Create Date: 2026-07-06 17:06:51.404677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'ffe809a51166'
down_revision: Union[str, Sequence[str], None] = '5504fbdc52c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review', 'comment',
               existing_type=mysql.FLOAT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('review', 'comment',
               existing_type=sa.String(length=255),
               type_=mysql.FLOAT(),
               existing_nullable=False)
    # ### end Alembic commands ###
